version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: hyfriend/hyfrienddb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
      - MYSQL_DATABASE=accounts

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest  # Corrected the environment variable name
      - RABBITMQ_DEFAULT_PASS=guest  # Corrected the environment variable name

  vproapp:
    build:
      context: ./Docker-files/app
    image: hyfriend/hyfriendapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: hyfriend/hyfriendweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
